
CC=g++
# CFLAGS=-I.

scytale: scytale.cpp
	mkdir -p demo
	$(CC) scytale.cpp simple_ciphers.cpp -o ./demo/scytale 

ceasar: ceasar.cpp
	mkdir -p demo
	$(CC) ceasar.cpp simple_ciphers.cpp -o ./demo/ceasar 
