
CC=g++
# CFLAGS=-I.

scytale: scytale.cpp
	mkdir -p demo
	$(CC) scytale.cpp simple_ciphers.cpp -o ./demo/scytale.out

caesar: caesar.cpp
	mkdir -p demo
	$(CC) caesar.cpp simple_ciphers.cpp -o ./demo/caesar.out
